#!/usr/bin/env bash

build_docker() {
  local image_dir="$1"
  local repository="$2"
  local version="$3"

  docker build \
    --tag "$repository:$version" \
    --tag "$repository:latest" \
    "$image_dir"
}
