#!/usr/bin/env bash

get_package_tag() {
  local folder="$1"
  local version="$2"
  local workspace_dir
  local filter_path

  workspace_dir="$(git rev-parse --show-toplevel)"
  filter_path="${folder#"$workspace_dir/"}"

  echo "$filter_path/v$version"
}
