[tool.commitizen]
version = "0.1.0"
name = "cz_filter_path"
version_scheme = "semver2"
tag_format = "devcontainer/images/node/$version"
ignored_tag_formats = ["*"]
filter_path = "devcontainer/images/node"
update_changelog_on_bump = true
