[tool.commitizen]
version = "0.1.1"
name = "cz_filter_path"
version_scheme = "semver2"
tag_format = "devcontainer/images/debian/$version"
ignored_tag_formats = ["*"]
filter_path = "devcontainer/images/debian"
update_changelog_on_bump = true
