[tool.commitizen]
version = "0.2.4"
name = "cz_filter_path"
version_scheme = "semver2"
tag_format = "devcontainer/features/cursor/$version"
ignored_tag_formats = ["*"]
filter_path = "devcontainer/features/cursor"
update_changelog_on_bump = true
version_files = [".cz.toml:version", "devcontainer-feature.json:version"]
