#!/usr/bin/env bash
set -euo pipefail

############################################################
######################## setup #############################
############################################################

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IMAGES_DIR="$(dirname "$SCRIPT_DIR")"
WORKSPACE_DIR="$(git rev-parse --show-toplevel)"

IMAGE="$1"
IMAGE_DIR="$IMAGES_DIR/$IMAGE"

############################################################
######################## sources ############################
############################################################

source "$WORKSPACE_DIR/.scripts/utils/log"
source "$WORKSPACE_DIR/.scripts/utils/has_release"
source "$WORKSPACE_DIR/.scripts/utils/bump_package"
source "$WORKSPACE_DIR/.scripts/utils/generate_changelog"
source "$WORKSPACE_DIR/.scripts/utils/get_version"
source "$WORKSPACE_DIR/.scripts/utils/get_package_tag"
source "$SCRIPT_DIR/utils/build_docker"

############################################################
######################## version ############################
############################################################

from_version="$(get_version "$IMAGE_DIR")"
increment="$(has_release "$IMAGE_DIR")"

if [ -z "$increment" ]; then
  echo "$IMAGE: no releasable changes" >&2
  exit 1
fi

info "$IMAGE: bumping version"

bump_package "$IMAGE_DIR" "$increment" >&2

new_version="$(get_version "$IMAGE_DIR")"
tag="$(get_package_tag "$IMAGE_DIR" "$new_version")"

success "$IMAGE: $from_version -> $new_version"

############################################################
###################### changelog ############################
############################################################

info "$IMAGE: generating changelog"

generate_changelog "$IMAGE_DIR" "$tag" >&2

############################################################
######################## build ##############################
############################################################

repository="ghcr.io/shotor/$IMAGE"

info "$IMAGE: building"

build_docker \
  "$IMAGE_DIR" \
  "$repository" \
  "$new_version" \
  >&2

success "$IMAGE: build complete"

############################################################
######################## return #############################
############################################################

success "$IMAGE: $tag"
echo "$tag"
