export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(
  git
  sudo
)

source $ZSH/oh-my-zsh.sh

export EDITOR=vim

export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_IE.UTF-8

path+=$HOME/.local/bin

alias ls='lsd'

alias DOITNOW='gaa && gcn! && gpf'
if ! command -v code >/dev/null 2>&1; then
  alias code='vscodium'
fi

eval "$(starship init zsh)"
