#!/usr/bin/env bash

commit_release() {
  local tags=("$@")
  local workspace_dir

  workspace_dir="$(git rev-parse --show-toplevel)"

  source "$workspace_dir/.scripts/utils/log"
  source "$workspace_dir/.scripts/utils/commit_release_message"

  local message
  message="$(commit_release_message "${tags[@]}")"

  ##########################################################
  ######################## commit ##########################
  ##########################################################

  info "Creating release commit"

  git commit -m "$message"

  success "Release commit created"

  ##########################################################
  ######################### tags ###########################
  ##########################################################

  info "Creating package tags"

  for tag in "${tags[@]}"; do
    git tag "$tag"
    success "  $tag"
  done

  ##########################################################
  ###################### batch tag #########################
  ##########################################################

  local batch_tag
  batch_tag="release/$(date -u +'%Y-%m-%dT%H-%M-%SZ')"

  info "Creating release batch"

  git tag "$batch_tag"

  success "$batch_tag"
}
