#!/usr/bin/env bash

commit_release_message() {
  local tags=("$@")
  local workspace_dir

  workspace_dir="$(git rev-parse --show-toplevel)"

  source "$workspace_dir/.scripts/utils/log"

  if [ "${#tags[@]}" -eq 0 ]; then
    error "No release tags provided"
    return 1
  fi

  local message="bump: release new versions"

  message+=$'\n'

  for tag in "${tags[@]}"; do
    local package="${tag%/*}"
    local version="${tag##*/}"

    message+=$'\n'"- $package -> $version"
  done

  printf '%s\n' "$message"
}
