#!/usr/bin/env bash

get_package_tag() {
  local package_dir="$1"
  local version="$2"
  local workspace_dir
  local relative_path

  workspace_dir="$(git rev-parse --show-toplevel)"
  relative_path="${package_dir#"$workspace_dir/"}"

  printf '%s/%s\n' "$relative_path" "$version"
}
