#!/usr/bin/env bash
set -euo pipefail

############################################################
######################## setup #############################
############################################################

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FEATURES_DIR="$(dirname "$SCRIPT_DIR")"
WORKSPACE_DIR="$(git rev-parse --show-toplevel)"

############################################################
######################## usage #############################
############################################################

usage() {
  cat <<EOF
Usage: $0 <feature> [source]

Publish a Dev Container feature.

Arguments:
  feature         Feature to release
  source          Optional feature source directory
                  Defaults to $FEATURES_DIR/<feature>

Options:
  -h, --help      Show this help message
EOF
}

############################################################
######################## parse #############################
############################################################

case "${1:-}" in
  -h|--help)
    usage
    exit 0
    ;;
  "")
    usage >&2
    exit 1
    ;;
esac

FEATURE="$1"
FEATURE_DIR="${2:-"$FEATURES_DIR/$FEATURE"}"

############################################################
######################## sources ############################
############################################################

source "$WORKSPACE_DIR/.scripts/utils/log"

############################################################
######################## release ############################
############################################################

info "$FEATURE: publishing"

devcontainer features publish \
  "$FEATURE_DIR" \
  -r ghcr.io \
  -n shotor/morgh \
  >&2

success "$FEATURE: published"
