[tool.commitizen]
version = "0.0.1"
name = "cz_filter_path"
version_scheme = "semver2"
tag_format = "devcontainer/features/apt-upgrade/$version"
ignored_tag_formats = ["*"]
filter_path = "devcontainer/features/apt-upgrade"
update_changelog_on_bump = true
version_files = [".cz.toml:version", "devcontainer-feature.json:version"]
