services:
  zot:
    image: ghcr.io/project-zot/zot-linux-amd64:v2.1.20
    ports:
      - "5000:5000"
    volumes:
      - /var/lib/zot:/var/lib/registry
    command:
      - serve
      - /etc/zot/config.json
    configs:
      - source: zot
        target: /etc/zot/config.json

configs:
  zot:
    file: ./config.json
