# vim:fileencoding=utf-8:foldmethod=marker

allow_remote_control      yes
confirm_os_window_close   0

font_family   FiraCode Nerd Font Mono
font_size     12

enable_audio_bell   no

background_opacity    1
background_blur       50

window_margin_width     0
window_padding_width    0 0

shell tmux new
