name: Release Batch

on:
  push:
    tags:
      - "release/**"

permissions:
  contents: read

jobs:
  collect:
    runs-on: ubuntu-latest

    outputs:
      tags: ${{ steps.collect.outputs.tags }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Collect
        id: collect
        run: |
          source .scripts/utils/get_release_tags

          tags="$(get_release_tags --json)"
          echo "tags=$tags" >> "$GITHUB_OUTPUT"

  release:
    needs: collect

    strategy:
      fail-fast: false
      matrix:
        tag: ${{ fromJSON(needs.collect.outputs.tags) }}

    uses: ./.github/workflows/release.yml
    with:
      tag: ${{ matrix.tag }}

    secrets: inherit
