name: Release Batch

on:
  push:
    tags:
      - "release/**"

  workflow_dispatch:
    inputs:
      tag:
        description: Release batch tag
        required: false
        type: string

permissions:
  contents: read
  packages: write

jobs:
  collect:
    name: Collect
    runs-on: ubuntu-latest

    outputs:
      docker-tags: ${{ steps.collect.outputs.docker-tags }}
      release-features: ${{ steps.collect.outputs.release-features }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Collect
        id: collect
        env:
          TAG: ${{ inputs.tag || github.ref_name }}
        run: |
          source .scripts/utils/get_release_tags

          tags="$(get_release_tags "$TAG" --json)"

          docker_tags="$(
            jq -c '
              map(select(startswith("docker/images/")))
            ' <<< "$tags"
          )"

          release_features="$(
            jq -r '
              any(.[]; startswith("devcontainer/features/"))
            ' <<< "$tags"
          )"

          echo "docker-tags=$docker_tags" >> "$GITHUB_OUTPUT"
          echo "release-features=$release_features" >> "$GITHUB_OUTPUT"

  docker:
    name: Release ${{ matrix.tag }}
    needs: collect
    if: ${{ needs.collect.outputs.docker-tags != '[]' }}

    strategy:
      fail-fast: false
      matrix:
        tag: ${{ fromJSON(needs.collect.outputs.docker-tags) }}

    uses: ./.github/workflows/release-docker.yml
    with:
      tag: ${{ matrix.tag }}

    secrets: inherit

  features:
    name: Release Dev Container Features
    needs: collect
    if: ${{ needs.collect.outputs.release-features == 'true' }}

    uses: ./.github/workflows/release-devcontainer-features.yml
    with:
      tag: ${{ inputs.tag || github.ref_name }}

    secrets: inherit
